"""Blind side-by-side listening page for several model checkpoints.

    uv run python tools/listening_page.py out.html name=path/to/model.pt name2=path/to/other.pt

The same requests (fixed seeds) are generated by every model; columns are shuffled and
labelled A, B, C ... with a reveal button, so melodies are judged before names are
known. Each cell renders the level with abcjs and has its own play button.
"""
from __future__ import annotations

import html
import json
import random
import sys
import warnings
from pathlib import Path

warnings.filterwarnings("ignore")

from mockingbird.export.formats import to_abc  # noqa: E402
from mockingbird.generate.service import LevelGenerator  # noqa: E402
from mockingbird.schema import GenerateRequest  # noqa: E402

REQUESTS = [
    dict(tonic="D", mode="major", meter="4/4", voice="S", difficulty=2, bars=8, style="folk", seed=11),
    dict(tonic="G", mode="major", meter="3/4", voice="A", difficulty=2, bars=8, style="chorale", seed=12),
    dict(tonic="F", mode="major", meter="4/4", voice="S", difficulty=3, bars=8, style="choral", seed=13),
    dict(tonic="A", mode="minor", meter="4/4", voice="A", difficulty=3, bars=8, style="chorale", seed=14),
    dict(tonic="Eb", mode="major", meter="2/4", voice="S", difficulty=2, bars=8, style="lied", seed=15),
    dict(tonic="E", mode="minor", meter="6/8", voice="T", difficulty=3, bars=8, style="folk", seed=16),
    dict(tonic="Bb", mode="major", meter="4/4", voice="B", difficulty=4, bars=12, style="choral", seed=17),
    dict(tonic="D", mode="minor", meter="3/4", voice="S", difficulty=4, bars=8, style="lied", seed=18),
]


def build(out: Path, models: dict[str, Path], seed: int = 0) -> None:
    names = list(models)
    rng = random.Random(seed)
    order = names[:]
    rng.shuffle(order)
    labels = {name: chr(ord("A") + i) for i, name in enumerate(order)}
    cells: dict[str, list[str]] = {}
    for name, path in models.items():
        gen = LevelGenerator(path)
        cells[name] = []
        for req in REQUESTS:
            try:
                level = gen.generate(GenerateRequest(**req))
                cells[name].append(to_abc(level, title=f"{labels[name]} · {req['style']} {req['tonic']} {req['mode']} {req['meter']} diff {req['difficulty']}"))
            except RuntimeError as e:
                cells[name].append(f"X:1\nT:{labels[name]} failed: {e}\nK:C\nz4|]")
        print(f"{name} -> {labels[name]}: {len(cells[name])} levels")
    columns = [{"label": labels[n], "abcs": cells[n]} for n in order]
    reveal = {labels[n]: n for n in names}
    page = f"""<!doctype html><html><head><meta charset="utf-8"><title>Listening test</title>
<script src="https://cdn.jsdelivr.net/npm/abcjs@6.4.4/dist/abcjs-basic-min.js"></script>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/abcjs@6.4.4/abcjs-audio.css">
<style>
body {{ font-family: system-ui, sans-serif; margin: 1rem; }}
.row {{ display: grid; grid-template-columns: repeat({len(columns)}, 1fr); gap: 1rem; margin-bottom: 1.5rem; border-top: 1px solid #ddd; padding-top: .5rem; }}
.cell {{ border: 1px solid #e5e5e5; padding: .4rem; border-radius: 6px; }}
.req {{ color: #555; font-size: .85rem; margin: .8rem 0 .3rem; }}
h3 {{ margin: .2rem 0; font-size: 1rem; }}
#reveal {{ margin: .5rem 0 1rem; }}
.abcjs-inline-audio {{ margin-top: .3rem; }}
</style></head><body>
<h2>Blind listening test</h2>
<p>Same request per row, one model per column. Play a cell, then compare across the row.
<button id="reveal">Reveal model names</button> <span id="names"></span></p>
<div id="rows"></div>
<script>
const columns = {json.dumps(columns)};
const reveal = {json.dumps(reveal)};
const requests = {json.dumps(REQUESTS)};
const rows = document.getElementById("rows");
requests.forEach((req, i) => {{
  const r = document.createElement("div"); r.className = "row";
  columns.forEach((col, j) => {{
    const c = document.createElement("div"); c.className = "cell";
    const id = `p${{i}}_${{j}}`, aid = `a${{i}}_${{j}}`;
    c.innerHTML = `<h3>Model ${{col.label}}</h3><div class="req">${{req.style}} · ${{req.tonic}} ${{req.mode}} · ${{req.meter}} · voice ${{req.voice}} · difficulty ${{req.difficulty}} · ${{req.bars}} bars</div><div id="${{aid}}"></div><div id="${{id}}"></div>`;
    r.appendChild(c);
    setTimeout(() => {{
      const visual = ABCJS.renderAbc(id, col.abcs[i], {{ responsive: "resize", add_classes: true }})[0];
      if (ABCJS.synth.supportsAudio()) {{
        const synth = new ABCJS.synth.SynthController();
        synth.load("#" + aid, null, {{ displayPlay: true, displayRestart: true, displayProgress: true }});
        synth.setTune(visual, false, {{ chordsOff: true }});
      }}
    }}, 0);
  }});
  rows.appendChild(r);
}});
document.getElementById("reveal").onclick = () => {{
  document.getElementById("names").textContent = Object.entries(reveal).map(([k, v]) => `${{k}} = ${{v}}`).join("   ·   ");
}};
</script></body></html>"""
    out.write_text(page, encoding="utf-8")
    print(f"wrote {out}; mapping {reveal}")


if __name__ == "__main__":
    out = Path(sys.argv[1])
    models = {kv.split("=", 1)[0]: Path(kv.split("=", 1)[1]) for kv in sys.argv[2:]}
    build(out, models)
